enum Statuses {
  IDLE = "IDING",
  STARTING = "STARTING",
  ENDING = "ENDING",
  QUESTIONING = "QUESTIONING",
  ANSWERING = "ANSWERING",
  ANSWERED = "ANSWERED",
  REVEALING_ANSWER = "REVEALING_ANSWER",
  LEADERBOARD = "LEADERBOARD",
}

export default Statuses;
